### ISSUE TITLE
File explorer panel background became black in Zed 0.164.2

### ISSUE THREAD

**Issue by avitkauskas** [gentlelionstudios/gentle-dark-zed#1]
Thanks for the nice theme!

After the update to Zed 0.164.2, file explorer panel background became black
I found that adding the following line into the theme makes it the right color again:

"surface.background": "#122330",

**Comment by brianjgamble** [comment]
I appreciate the compliment and thanks for letting me know!  I submitted a PR to add that color and I fixed a couple of other things as well.
